version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: vladaslanov
      MONGO_INITDB_ROOT_PASSWORD: vlad1213
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: express_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb+srv://vladaslanov:vlad1213@reas.e7lvz.mongodb.net/leadsDB?retryWrites=true&w=majority
    volumes:
      - ./server:/app/server
      - /app/server/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5137:5137"
    stdin_open: true
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  mongo_data:
